### ISSUE TITLE
Simplify tests using `assert_sample_output`, no more entries and regexes

### ISSUE THREAD

**Issue by alexmojaki** [cool-RR/PySnooper#115]
Tests using `assert_sample_output` are much easier and faster to read, write, and maintain. No regexes. Much less thinking and typing required. Much more concrete, no abstractions. I think it would be a huge improvement to migrate all tests related to tracing to this style. Meanwhile tests relating to output methods should focus only on testing the output, similar to what I've done in #103. We can get rid of `assert_output` and the entries framework entirely.

**Comment by cool-RR** [comment]
Interesting. Can you give a list of disadvantages that these tests would
have over the entries framework?

**Comment by alexmojaki** [comment]
In some scenarios a change to the implementation might result in a large batch of tests needing updating that may not be needed in the entries framework. This is pretty simple mindless copy-pasting, so I don't think it's a problem. I could probably write a script to automate it. And I think it would be good to have a clear diff showing how a change affects the output in various situations.

Occasionally, not being able to specify things like value_regex might make things a little harder, but not much. Some regexes in the normalise function instead, maybe a bit of patching, and it should be fine.

**Comment by cool-RR** [comment]
Okay, thanks. It might take me a while to get to this.

**Comment by alexmojaki** [comment]
I'm willing to do this.

**Comment by cool-RR** [comment]
I understand, that's good. I'll need a while to think about it anyway, so I
suggest you wait until I update here.
