### ISSUE TITLE
How to use `get_shortish_repr` to get the shape of vectors?

### ISSUE THREAD

**Issue by JiahaoYao** [cool-RR/PySnooper#121]
Hi @cool-RR, could you show how to make use of `get_shortish_repr`  to let the `snooper` show the shape of vectors, as you said in #94?

**Comment by cool-RR** [comment]
Try to monkeypatch the `__repr__` method of the array class

**Comment by JiahaoYao** [comment]
Hi @cool-RR, could you give me an example about that?

I also google monkey patch, I find the https://gist.github.com/gseverina/6713629. Do you mean like this? 

```
class Person:
    """Represents a Person"""
    def __init__(self,name):
        self.name = name

    def __repr__(self):
        return str(self.name)

#just a method outside the Person scope...
def upper_name(self):
    return (self.name).upper()

if __name__ == "__main__":
    j = Person("John")
    p = Person("Peter")
    print(j)
    print(p)
    j.__repr__ = upper_name
    print(j) # John
    print(j.__repr__(j)) # JOHN
```

**Comment by cool-RR** [comment]
Yes, that's what I meant.

**Comment by JiahaoYao** [comment]
Hi @cool-RR, thank you for your reply. I mean I still failed to monkey patch because `print(j)` still use the **old** `__repr__`, only by using `print(j.__repr__(j))` can be the new method.

**Comment by alexmojaki** [comment]
You have to patch the class. Assigning magic methods to an instance doesn't work, because functions like `repr` look them up on the class.

**Comment by JiahaoYao** [comment]
Oh, I see. thank you @alexmojaki. Then, my question is how to monkey patch the class of ,say, numpy.ndarray. 

```

import numpy as np 

def return_no():
    return "abc"

np.ndarray.__repr__ = return_no

a = np.random.normal(0, 0.1, [10, 20])
print(a)
```

What I got is

```
Traceback (most recent call last):
  File "test_monkeypatch.py", line 28, in <module>
    np.ndarray.__repr__ = return_no
TypeError: can't set attributes of built-in/extension type 'numpy.ndarray'
```

**Comment by alexmojaki** [comment]
Well, you could try using [forbiddenfruit](https://github.com/clarete/forbiddenfruit)...

I don't actually understand the suggestion to patch `ndarray.__repr__`. Rather, you could patch the `get_shortish_repr` function in `pysnooper.utils`.

**Comment by cool-RR** [comment]
Right, looks like `ndarray` can't be patched because it's a C extension. @alexmojaki 's two suggestions are good, try them.

**Comment by JiahaoYao** [comment]
That is pretty cool. Thanks, @alexmojaki and @cool-RR.
