### ISSUE TITLE
Chinese coding problem

### ISSUE THREAD

**Issue by nocmt** [cool-RR/PySnooper#124]
I use python3.7，It default coding  is 'utf-8', So I didn't add "#-*-coding: utf-8-*-" to the first line of my file.

But when I used PySnooper, I found an error:

      `UnicodeEncodeError: 'gbk' codec can't encode character '\ufffd' in position 69: illegal multibyte sequence`

**Code location：tracer.py 134th line**

My solution is:

```
# tracer.py 134 line
def write(self, s):
        - with open(self.path, 'w' if self.overwrite else 'a') as output_file:
       + with open(self.path, 'w' if self.overwrite else 'a', encoding='utf-8') as output_file:
            output_file.write(s)
        self.overwrite = False
```

and add "#-*-coding: utf-8-*-" in my file

I look forward to better solutions, Thanks.

**Comment by cool-RR** [comment]
Great, thanks for the fix suggestion! Can you also include a reproducible sample, so I could add a test for this?

**Comment by alexmojaki** [comment]
Can you check if the fix works without `#--coding: utf-8--`? I think this is just because `gbk` is the default encoding on your computer, and it doesn't know how to encode that character.

**Comment by nocmt** [comment]
> Great, thanks for the fix suggestion! Can you also include a reproducible sample, so I could add a test for this?

I found this problem in pytest's assertion

test_demo.py

```Python
import pysnooper
import pytest

@pysnooper.snoop('./run.log')
def test_demo():
    a = 1
    assert a == 1, '失败'
```

>pytest test_demo.py::test_demo

![image](https://user-images.githubusercontent.com/26828323/57999410-ec3e3c80-7b07-11e9-9e46-1024adc89737.png)

**Comment by cool-RR** [comment]
I fixed the problem and added a test, please upgrade PySnooper and give it a try.
