### ISSUE TITLE
Add `python` and `debug` tags to repository

### ISSUE THREAD

**Issue by techtonik** [cool-RR/PySnooper#125]
To make it easily discoverable.

https://github.com/search?q=topic%3Apython+topic%3Adebug

**Comment by cool-RR** [comment]
Good idea, done. Thank you!

**Comment by techtonik** [comment]
I'd also add `pdb` for people who are still using that tool.

**Comment by cool-RR** [comment]
I disagree, but thanks for the suggestion.
