### ISSUE TITLE
No tags in release

### ISSUE THREAD

**Issue by guysoft** [cool-RR/PySnooper#128]
Hey,
I can see you are changing the release versions, but there are no tags in the Repo,
It would also let you post to the release page what has changed and if there is anything major.
Example:
https://github.com/python/cpython/releases

And if you feel like it you can add more text:
https://github.com/guysoft/OctoPi/releases

**Comment by cool-RR** [comment]
That'd be good, but I don't want the effort and commitment of tagging every
time. If there was a bot that automatically tagged based on the version in
the Python files, that'd be cool.

In any case thanks for documenting this here, we might do this in the
future.

**Comment by guysoft** [comment]
If you are releaseing to PyPi already then you can use this:
https://github.com/user-cont/release-bot

**Comment by cool-RR** [comment]
Interesting, thanks for sending.

**Comment by keszybz** [comment]
+1 here: it'd be great if releases were tagged with git tags.

BTW: I'm preparing a package for Fedora (https://bugzilla.redhat.com/show_bug.cgi?id=1720843) after seeing your lighting talk at pycon.cz.

**Comment by cool-RR** [comment]
Bah, you convinced me :)

I pushed the version tags now, and I'll try to remember to include them in future releases. If I forget to push them in the future, let me know. Thanks for packaging for Fedora! I saw that it's finished, that's great!
