### ISSUE TITLE
About the 'with' position

### ISSUE THREAD

**Issue by ballgodpy** [cool-RR/PySnooper#133]
![image](https://user-images.githubusercontent.com/24569445/60392300-9317ee80-9b32-11e9-9548-83806bb16f57.png)
q1:why  line 14 'with' is lined up with line 11'for', not  line 12 ?
q2: why the output  only shows when i ==  2,  
![image](https://user-images.githubusercontent.com/24569445/60392325-edb14a80-9b32-11e9-959c-639f5885f0d9.png)

I want to know the reason,thank you

**Comment by cool-RR** [comment]
I ran your code and got the right result:

```
New var:....... lst = [676, 23, 480]
New var:....... i = 2
13:59:58.099355 line        12         lower = min(lst)
New var:....... lower = 23
13:59:58.099355 line        13         upper = max(lst)
New var:....... upper = 676
13:59:58.099355 line        14         mid = (lower + upper) / 2
New var:....... mid = 349.5
13:59:58.100356 line        15         print(lower, mid, upper)
23 349.5 676
```

I think that your problem isn't the code but the way that you run it. I don't know this `runfile` function but I guess it's clashing with PySnooper in some way.

**Comment by alexmojaki** [comment]
I think OP is using PyCharm to run a file inside a console. The console persists the source cache which is out of date after changing the file.

**Comment by cool-RR** [comment]
Makes sense.
