### ISSUE TITLE
Question : How do I only focus on function calls and return values?

### ISSUE THREAD

**Issue by 625781186** [cool-RR/PySnooper#136]
I find that many open source projects do not have UML diagrams, making the functions called difficult to trace.

So, How do I only focus on function calls and return values,  not variables?
Like this :
![image](https://user-images.githubusercontent.com/30521429/60743005-2d988780-9fa2-11e9-8774-dfbd10a2c45f.png)

I want to just keep the calls and returns.

**Comment by cool-RR** [comment]
grep?

**Comment by 625781186** [comment]
@cool-RR 
Sorry , I don't quite understand.
I just filter lines of `call` and `return`
![image](https://user-images.githubusercontent.com/30521429/60743496-76e9d680-9fa4-11e9-9080-32b1e8d226d6.png)

**Comment by alexmojaki** [comment]
There are many libraries that offer functionality like this. Google "python call graph" and you'll find several. https://github.com/zestyping/q also comes to mind, using the `@q` decorator. It's not a very complicated thing to do, you can even do it yourself:

```python
import sys
import inspect


def trace(frame, event, arg):
    indent = ' ' * 4 * len(inspect.stack())
    if event == 'call':
        print(indent + 'Calling ' + frame.f_code.co_name)
    elif event == 'return':
        print(indent + 'Returning ' + repr(arg))
    return trace


sys.settrace(trace)


def factorial(n):
    if n <= 1:
        return 1
    return n * factorial(n - 1)


factorial(5)
```

Output:

```
            Calling factorial
                Calling factorial
                    Calling factorial
                        Calling factorial
                            Calling factorial
                            Returning 1
                        Returning 2
                    Returning 6
                Returning 24
            Returning 120
```

PySnooper is all about those lines and variables in the middle. If you don't care about that stuff *at all*, I don't think this is the right tool. If you want some kind of combination, e.g. the full output for top level calls but just the calls and returns after some depth, then that might be a feature worth adding.

**Comment by 625781186** [comment]
@Alex Hall 
Thanks .
As I said, I just want to track the deep call flow of the main function.
![image](https://user-images.githubusercontent.com/30521429/60743875-fcba5180-9fa5-11e9-97ae-8c14111fd5e1.png)

**Comment by alexmojaki** [comment]
Is https://github.com/gak/pycallgraph suitable?

**Comment by 625781186** [comment]
> 是https://github.com/gak/pycallgraph合适？

Yes, like this .
I know pycharm has the function , but it's not as thorough as pysooner tracks. 
I don't know if it's my unfamiliarity with them .
I want to use `pysnooper` for the reason that tracing is very deep.
