### ISSUE TITLE
Need fewer logs when in a loop

### ISSUE THREAD

**Issue by Fangyh09** [cool-RR/PySnooper#137]
```python
@pysnooper.snoop()
def foo_loop(number):
  result = []
  for i in range(number):
    result.append(i * 10)
```
For foo_loop(1000), `result` will be updated 1000 times.
But I only want to know the final result.

**Comment by cool-RR** [comment]
Start by modifying your communication skills ;)

You need to be much, much clearer in communicating your problem.

**Comment by Fangyh09** [comment]
@cool-RR Okay, updated.

**Comment by cool-RR** [comment]
Looks like PySnooper isn't the right tool for this job.

**Comment by alexmojaki** [comment]
This is pretty much exactly the example use case for `with pysnooper.snoop():` given early on in the README. Does that not suit you?
