### ISSUE TITLE
Problem with passing in a single tuple in custom_repr= ()

### ISSUE THREAD

**Issue by DavidykZhao** [cool-RR/PySnooper#144]
I was trying it on a toy example and just wanted to pass in one tuple like 
(list, print_list_size) to custom_repr= () with print_list_size being the example used in the readme file:
`
def print_list_size(l):
    return 'list(size={})'.format(len(l))
`

There was an exception:" TypeError: cannot unpack non-iterable function object." 
I think the problem lies in that custom_repr is a tuple of tuples thus when it has only one element it won't be unpacked successfully. 
I changed custom_repr = [ ] and then put in the tuple (list, print_list_size) and it worked. Or, put an extra , in the tuple such like this:
`
@pysnooper.snoop(custom_repr = ( (list, print_list_size), ))
`

Just a small issue but hopefully this would be beneficial for other people.

**Comment by alexmojaki** [comment]
@cool-RR I can't be bothered with an actual PR, but something like this in the Tracer class should do:

    if custom_repr and callable(custom_repr[0]):
        custom_repr = [custom_repr]

FYI @DavidykZhao [snoop](https://github.com/alexmojaki/snoop) will show you the `len()` of most things out of the box in addition to the usual repr.

**Comment by DavidykZhao** [comment]
@alexmojaki That's something I am thinking about as well. Thanks for the suggestion. Looking forward to new features.
