### ISSUE TITLE
Fluentbit error: or: Could not open configuration file. Aborting

### ISSUE THREAD

**Issue by SripriyaMenon** [cool-RR/PySnooper#163]
I am trying to configure Fluentbit on my 5 node EKS cluster.

It was running ok when i was running it on the 3 node cluster. But now after upgrading it to 5 node cluster, The pods are always in the CrashLoopBack State and the logs mention:

Fhdjghjiegfi;ugue~]$ kubectl logs ds/fluent-bit -n logging
Found 5 pods, using pod/fluent-bit-6qzcp
Fluent Bit v1.1.0
Copyright (C) Treasure Data

Error: Could not open configuration file. Aborting

I dont know if there is something that needs to be modified in the config file also

**Comment by cool-RR** [comment]
Toto, we're not in Kansas anymore! :D
