### ISSUE TITLE
Help: trouble with "SOURCE UNAVAILABLE"

### ISSUE THREAD

**Issue by samhld** [cool-RR/PySnooper#164]
Overall, this is working for me but instead of getting the line of code that's being evaluated, I'm getting a constant `SOURCE UNAVAILABLE` message.  It looks like this is called from [here](https://github.com/cool-RR/PySnooper/blob/master/pysnooper/tracer.py#L89).  Not sure why it's not a "source" though.  Can you help?  Thanks!

This is happening on a very basic function, say:
```
@pysnooper.snoop()
def hello(name):
     print(f"Hello, {name}")
```

Returns:
```
> hello('sam')
Source path:... <stdin>
Starting var:.. name = 'sam'
17:27:50.065066 call         1 SOURCE IS UNAVAILABLE
17:27:50.065288 line         3 SOURCE IS UNAVAILABLE
Hello, sam
17:27:50.065439 return       3 SOURCE IS UNAVAILABLE
Return value:.. None
```

**Comment by cool-RR** [comment]
What's the scenario? Where is your function defined? In a code file, in a
shell, and if so what shell?

**Comment by samhld** [comment]
@cool-RR it's defined in a python3 interactive shell.  Sounds like maybe I don't understand what "source" means in this case?

**Comment by alexmojaki** [comment]
The source code isn't saved anywhere in a regular shell. If you write code that raises an exception you'll see that code doesn't show in the traceback either.

**Comment by cool-RR** [comment]
@alexmojaki is correct. If you were to suggest to python-ideas to start saving source code on code objects, I would support that suggestion, and that would make this feature possible. I think that they're unlikely to accept it, but let me know if you try.

**Comment by samhld** [comment]
thanks, guys!  Clears that up.
