### ISSUE TITLE
Unnecessary BaseVariable type in watch?

### ISSUE THREAD

**Issue by chen-chao** [cool-RR/PySnooper#165]
Is `isinstance(v, BaseVariable)` here really necessary?  `v` shouldn't be an instance of `BaseVariable` since it has abstract methods.

https://github.com/cool-RR/PySnooper/blob/c0bf4bd0067d8d7618e40d27b2626e6f3cba4fce/pysnooper/tracer.py#L207-L213

**Comment by alexmojaki** [comment]
If v is an instance of a subclass of BaseVariable, `isinstance(v, BaseVariable)` will be True.

I'm pretty sure if you remove that check you will find some tests fail.

**Comment by chen-chao** [comment]
Thanks for your answer. Learned a lot from the source code.
