### ISSUE TITLE
Bug: wrong when using

### ISSUE THREAD

**Issue by CLannadZSY** [cool-RR/PySnooper#167]
### use print(), can output correctly
![Snipaste_2019-10-29_14-49-44](https://user-images.githubusercontent.com/38000492/67744093-890fe900-fa5b-11e9-8ccd-e429e9bca8c6.png)

### use pysnooper,it wrong
![Snipaste_2019-10-29_14-52-51](https://user-images.githubusercontent.com/38000492/67744205-d55b2900-fa5b-11e9-9478-2f1e647bc0ab.png)

### why?

**Comment by alexmojaki** [comment]
PySnooper requires `()` in the decorator, i.e. `@pysnooper.snoop()`. [My version](https://github.com/alexmojaki/snoop) doesn't.

**Comment by CLannadZSY** [comment]
so sorry, I am too careless.
