### ISSUE TITLE
feature request: support ndarrays

### ISSUE THREAD

**Issue by TejasAvinashShetty** [cool-RR/PySnooper#175]
Is there a way to use pysnooper with ndarrays from numpy?

**Comment by alexmojaki** [comment]
If you want the variables to display properly, try https://github.com/alexmojaki/snoop

**Comment by cool-RR** [comment]
This won't be implemented in PySnooper, sorry. I think it's too specialized, and not worth the added complexity. People should use either a real debugger, or a real monitoring solution.
