### ISSUE TITLE
Delta Time Instead of Relative Time

### ISSUE THREAD

**Issue by Lazloo** [cool-RR/PySnooper#194]
I would appreciate an option that shows the relative spend time for each line. That is the delta time to the previous line.

That would be great
Lazloo

**Comment by cool-RR** [comment]
I understand and I see how that can be useful, but I think I'm gonna rule this out. It's important to keep PySnooper simple and resist the temptation to add too many features. Otherwise it'll become just another debugger.

**Comment by cool-RR** [comment]
Thanks anyway for suggesting this.
