### ISSUE TITLE
Frozen Implementation Fails

### ISSUE THREAD

**Issue by diVineProportion** [cool-RR/PySnooper#215]
when freezing with pyinstaller (single file) on windows a `NameError: name 'copyright' is not defined` appears. Not sure if this is an issue with hidden imports or hooks, but I wasn't able to get it to work with a simple 
```py
import snoop

@snoop
def counter(start, end):
    for i in range(start, end):
        print(i)
        
if __name__ == "__main__":
    counter(1, 1000)
```

**Comment by cool-RR** [comment]
I believe this belongs here: https://github.com/alexmojaki/snoop

**Comment by alexmojaki** [comment]
@diVineProportion I've just pushed a fix for this, upgrade to the latest version of `cheap_repr` which is where the error comes from. If that doesn't work, open an issue on https://github.com/alexmojaki/snoop or https://github.com/alexmojaki/cheap_repr.
