### ISSUE TITLE
pypi has 1.0.0 has there is no tag in the repo

### ISSUE THREAD

**Issue by keszybz** [cool-RR/PySnooper#221]
C.f. https://pypi.org/project/PySnooper/1.0.0/ .

**Comment by cool-RR** [comment]
Oops, my bad. Fixed.

I'm curious, what are the effects of a missing tag?

**Comment by keszybz** [comment]
I used the tarball download in the Fedora package (https://src.fedoraproject.org/rpms/python-pysnooper). The pypi download works too, and I can trivially switch to that, but I wanted to verify that the tarball on pypi is legit.

**Comment by cool-RR** [comment]
Cool, thanks for reporting.
