### ISSUE TITLE
print value of a claas var

### ISSUE THREAD

**Issue by smjaberl** [cool-RR/PySnooper#227]
Hi,

just have a look on this simple code example:

> import pysnooper
> 
> class test:
>     @pysnooper.snoop()
>     def __init__(self):
>         a=10
>         self.b = 12 / 3
>         c = a / 2
>         a = c
> 
> test()

the output of pysnooper is this 

> Source path:... /workspaces/pysnooper-test.py
> Starting var:.. self = <__main__.test object at 0x7f5b75c6ab60>
> 23:39:15.038150 call         5     def __init__(self):
> 23:39:15.038330 line         6         a=10
> New var:....... a = 10
> 23:39:15.038350 line         7         self.b = 12 / 3
> 23:39:15.038387 line         8         c = a / 2
> New var:....... c = 5.0
> 23:39:15.038405 line         9         a = c
> Modified var:.. a = 5.0
> 23:39:15.038428 return       9         a = c
> Return value:.. None

I think it would be very nice, if I could see the value of self.b as well as  the value of a, c, and d.

**Comment by cool-RR** [comment]
`pysnooper.snoop(watch=('self.b',))`
