### ISSUE TITLE
Use Tox for running tests

### ISSUE THREAD

**Issue by bittner** [cool-RR/PySnooper#23]
We should add a Tox configuration (`tox.ini`) to allow running all tests locally, and use `tox-travis` in the CI configuration to make the expansion automatic.

Here are a few examples to see how that's meant to work:

- https://github.com/vshn/concierge-cli
- https://github.com/bittner/pyclean
- https://github.com/mdgart/sentrylogs
- https://github.com/jazzband/django-analytical
- https://github.com/behave/behave-django

Note that this also allows to encapsulate the test requirements into `tox.ini` (and subsequently can make the test requirements file unnecessary :+1:).

**Comment by cool-RR** [comment]
I was a bit reluctant to use tox because reading the travis-ci docs, I understand that it's a bit different than how Travis natively runs. Also running tox locally would require installing all Python versions locally, right? That sucks.

**Comment by bittner** [comment]
Running all tests locally has a significant advantage: You know what breaks before you push code. And it's faster.

Installing several Python versions locally is easy with [pyenv](https://github.com/pyenv/pyenv). This is a very popular software. Everyone who does package development that spans several Python versions should use it.

As an alternative to installing _all_ Python versions locally you can run Tox against just the versions you have already installed or are comfortable installing. It goes this way:

```console
$ tox -e py36,py27
```

The remaining environments can still run on the CI service.

**Comment by cool-RR** [comment]
Okay. If you'll implement it, I'll merge it.

**Comment by lockwooddev** [comment]
@bittner You might as well use drone.io which can run the various versions inside docker. 
Tox became obsolete for me after I discovered drone. For open source they offer https://cloud.drone.io/

**Comment by bittner** [comment]
> Tox became obsolete for me after I discovered drone.

This makes you dependent on Drone. It's your choice of course.

**Comment by cool-RR** [comment]
I'm wary of depending on external services. Thanks for the suggestion anyway @lockwooddev , it's appreciated.

Tox is pretty mature. Peter, feel free to go ahead if you wish.

**Comment by 1138-4EB** [comment]
> As an alternative to installing _all_ Python versions locally you can run Tox against just the versions you have already installed or are comfortable installing.

It is also possible to use official containers: https://hub.docker.com/_/python. On the one hand, it avoids installing different python versions on the host. On the other hand, the results you get locally are exactly the same as what the CI service (Travis) will produce.

> This makes you dependent on Drone. It's your choice of course.

The choice between Drone, Travis or any other CI service that is able to run docker containers is not relevant. The dependency that @lockwooddev proposed (implicitly) is docker.

**Comment by bittner** [comment]
@lockwooddev @1138-4EB You're both right.

The main reason to prefer a Python technology before getting help with other technology is to both lower the barrier for Python developers and stick to common Python practices.

Using Docker is always a valid choice, nowadays, and it's good that you point out the possibilities. Thank you!
