### ISSUE TITLE
Compatibility issue with Debugger in Visual Studio Code

### ISSUE THREAD

**Issue by fertingoff** [cool-RR/PySnooper#232]
Thanks for the amazing tool. I use it every day.

I'm facing a possible compatibility issue when using Visual Studio Code. If I switch off pysnooper, default debugging works as intended.

The error I see while trying to debug with debugger (not with breakpoint()):

PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/Users/.../venv/lib/python3.10/site-packages/pysnooper/tracer.py", line 355, in __exit__
    sys.settrace(stack.pop())

Any tips would be appreciated.

**Comment by cool-RR** [comment]
PySnooper uses the same mechanism as a debugger, so it can't be used together with a debugger. Making this work will require a change to cpython.
