### ISSUE TITLE
`return` event line missing when exception occurred

### ISSUE THREAD

**Issue by yantaozhao** [cool-RR/PySnooper#242]
When exception occurred, the `return` event is not recorded in snoop log. This leaves an unbalanced `call-return` pairs.

**Expected behavior**: all ***event*** should properly be recorded even though exception happened.

demo code:
```python
import pysnooper

def bar(a, b):
    return a + b

def baz():
    try:
        x = 'hi' + 1  # exception here!
        return 1
    except:
        raise  # <- return event missing
    return -1

def foo():
    r = bar(2, 3)
    print(r)
    return r

@pysnooper.snoop(depth=2, normalize=True)
def main():
    foo()
    try:
        baz()
    except:
        pass

main()
```

![image](https://github.com/cool-RR/PySnooper/assets/9587405/3b16cb52-f78d-4f5c-863d-64a66c4d98c5)

In the above demo, `return` event in _line 13_ is not recorded like _line 20_ do. the `call-return` pair is broken.

**Comment by cool-RR** [comment]
Which versions of PySnooper and Python? And what OS?

**Comment by yantaozhao** [comment]
python 3.10, PySnooper 1.2.0, all platforms

**Comment by cool-RR** [comment]
Ah, it's possible that I have just caused this bug with this most recent version. I'll look into it.

**Comment by cool-RR** [comment]
If you're interested in writing a failing test case, that'll be helpful.

**Comment by yantaozhao** [comment]
commit a PR to resolve this issue.

**Comment by cool-RR** [comment]
Can you explain why there should be a `return` line when an exception is raised? Can you explain what practical problem it causes that this line doesn't exist?

**Comment by yantaozhao** [comment]
> Can you explain why there should be a return line when an exception is raised?

No matter exception raised or not, all `return` event should be recorded because it really happened. It make things easy to write a log analyser as the `call-return` pairs are balanced.

> Can you explain what practical problem it causes that this line doesn't exist?

For log readable, consider below example:
```python
import pysnooper


def bar(a, b):
    return a + b


def baz():
    try:
        x = 'hi' + 1  # exception here!
        return 1
    except:
        raise
    finally:  # <-do something and output
        a=1
        b=2
        c=a+b
        foo()
    return -1


def foo():
    r = bar(2, 3)
    print(r)
    return [8]


@pysnooper.snoop(depth=9, normalize=True)
def main():
    try:
        baz()
    except:
        pass


main()
```

![image](https://github.com/cool-RR/PySnooper/assets/9587405/76fdcab2-00fd-46f5-97b7-9637b69c7c2b)

if `return 18` was not recorded, athough it can, but will spend more time to find that the code ran to and returned from `line 18`.

**Comment by alexmojaki** [comment]
> It make things easy to write a log analyser

It sounds like you might prefer using something like https://github.com/ionelmc/python-hunter. Or just writing your own function for `sys.settrace`.

**Comment by cool-RR** [comment]
@yantaozhao Sorry, I'm not seeing the practical usage here. It actually sounds misleading to write "return" when a function exited because of an exception rather than returned a value. I'm not sure what your use case is, but it sounds like it's a very niche use case that's not worth compromising for.
