### ISSUE TITLE
Suggestion: use ncurses to update values in place

### ISSUE THREAD

**Issue by kootenpv** [cool-RR/PySnooper#25]

**Comment by cool-RR** [comment]
This sounds interesting, but I don't fully understand. Could you please elaborate?

**Comment by kootenpv** [comment]
Sorry... I was doing a simple

```
@snoop()
def fn():
    for i in range(100):
        a = i
```

And this will clutter your output.

If you would use `ncurses1, you could perhaps update the value in place. under the line.

**Comment by cool-RR** [comment]
Ah, that would be more interactive, right? Not really a text dump, but something more like a GUI. I'm against it, this tool needs to stay simple.
