### ISSUE TITLE
Feature request: Print line containing actual function name for "call" event

### ISSUE THREAD

**Issue by czietz** [cool-RR/PySnooper#28]
When the function decorator `@pysnooper.snoop()` is in a separate line, the "call" event will print that line instead of the one containing the actual function name. This can be seen in the example in README.md:
https://github.com/cool-RR/PySnooper/blob/master/README.md#example

While this is technically correct (for Python the function definition starts with the decorator), it would make traces easier to read if the actual function name was printed. Maybe a special case could be added for "call" events: if the source line reported by Python only contains the decorator, print the next source line instead.

**Comment by cool-RR** [comment]
Agreed. This seems to be a weakness in Python's introspection ability. I'll be happy to look at a pull request, except I'll need to be reasonably sure it won't backfire in other cases.

**Comment by czietz** [comment]
Since Python syntax (https://docs.python.org/3/reference/compound_stmts.html#function-definitions) stipulates that each decorator must end with a new line and, therefore, the actual function name cannot be in the same line, it should be rather easy to skip decorator lines without accidentally skipping too much.

I'll send a pull request later today.

**Comment by cool-RR** [comment]
Great, and I'll want tests too. (Feel free to amend the existing tests, if
you'll need help let me know.)
