### ISSUE TITLE
add a switch for this decorator

### ISSUE THREAD

**Issue by 836304831** [cool-RR/PySnooper#49]

**Comment by cool-RR** [comment]
More details please.

**Comment by 836304831** [comment]
maybe add a switch for this decorator will be better. 
We develop a project has two model: development environment and production environment，generally speaking，we want to this decorator works for dev environment, not production environment. if add a switch,  we can close this decorator in production environment and not comment the decorator. 

like this:
def snoop(output=None, variables=(), depth=1, prefix='', switch=True):
    write = get_write_function(output)
    @decorator.decorator
    def decorate(function, *args, **kwargs):
        target_code_object = function.__code__
        if switch:
            with Tracer(target_code_object=target_code_object,
                        write=write, variables=variables,
                        depth=depth, prefix=prefix):
                return function(*args, **kwargs)
        else:
            return function(*args, **kwargs)

    return decorate

**Comment by cool-RR** [comment]
I'm against that. Changing to `switch=False` is about as easy as commenting out or removing the decorator, and the latter is much clearer. This is a tool for debugging, not meant to be checked into Git or used in production.

**Comment by 836304831** [comment]
I need remove the decorotor befor deploy my project to production environment if I use this decorator for debugging, this process need to modify code(maybe just remove the decorator), maybe It will bring out unpredictable errors or exceptions.

**Comment by cool-RR** [comment]
It's normal that you'd remove the decorator before deploying to production.

**Comment by 836304831** [comment]
ok, thanks.
