### ISSUE TITLE
Ability to overwrite to log file instead of only appending

### ISSUE THREAD

**Issue by Kandeel4411** [cool-RR/PySnooper#5]
Would  be nice if we could overwrite existing log files

**Comment by cool-RR** [comment]
Nice idea, feel free to submit a pull request. Probably just truncate the
file when the function begins.

**Comment by cool-RR** [comment]
If you're submitting a pull request, I'd require it to include tests.

**Comment by Cruuncher** [comment]
Can't you just open the file with a different mode? 'w' instead of 'a'?

**Comment by cool-RR** [comment]
No because I reopen on every write.

**Comment by 836304831** [comment]
I feel this idea "Ability to overwrite to log file instead of only appending" is very nice, but after I clone the repo today, unfortunately,  I found this idea has not implemented.

**Comment by cool-RR** [comment]
@836304831 feel free to submit a pull request
