### ISSUE TITLE
Feature request: Support for jupyterlab

### ISSUE THREAD

**Issue by jmanz1111** [cool-RR/PySnooper#63]
Thanks for providing support for Ipython and Jupyter.  Could you also provide support for jupyterlab?  Seems like the same issue is still occurring there:

[error msg.txt](https://github.com/cool-RR/PySnooper/files/3121749/error.msg.txt)

**Comment by cool-RR** [comment]
You're using an old version of PySnooper. Please upgrade and report back.

**Comment by jmanz1111** [comment]
Yep, upgrading to 0.0.22 did the trick. Apologize about the false positive. Thanks!
