### ISSUE TITLE
Bug when outputting special characters to shell

### ISSUE THREAD

**Issue by rtphokie** [cool-RR/PySnooper#67]
Noticed this error while snooping on a function that handles Unicode strings, pysnooper seems unhappy about the degree symbol here:

  File "weather.py", line 390, in graphic_single
    'location 1': u"%dºC / %dºF" % (round(data[sol]['max_temp']), 
  File "/Users/userid/Library/Python/2.7/lib/python/site-packages/pysnooper/tracer.py", line 184, in trace
    '{frame.f_lineno:4} {source_line}'.format(**locals()))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xba' in position 33: ordinal not in range(128)

**Comment by cool-RR** [comment]
I think this isn't about PySnooper and unicode, it's about your shell not supporting the unicode characters. Please give a full reproduceable example.

**Comment by cool-RR** [comment]
Also, your Python version.

**Comment by cc20101001** [comment]
I had the same problem before in python2.7 before，give a full reproduceable example，let me try it，thanks

**Comment by cc20101001** [comment]
d = "s*&F.。、]}】df" 

i find the problem

in python2.7，Sometimes format not easy to use than %

use % replace format can resolve the problem

**Comment by cool-RR** [comment]
I reject #77. I won't change my string formatting method without proof that it's the cause of the problem. I'm waiting for a full reproducible example.

**Comment by cc20101001** [comment]
# coding=utf-8
from pysnooper import pysnooper


@pysnooper.snoop()
def test_format():
    d = "s*&F.。、]}】df"
    return d


test_format()

# you can try it in python2.7

**Comment by alexmojaki** [comment]
I think it makes sense to add the `u` prefix as you've done in #77. I think you're confusing everyone by talking about the `.format` method and `%`, which is unrelated.

**Comment by cc20101001** [comment]
i'm sorry

> I think it makes sense to add the `u` prefix as you've done in #77. I think you're confusing everyone by talking about the `.format` method and `%`, which is unrelated.

i'm sorry

**Comment by cool-RR** [comment]
I was able to replicate the problem on my machine, thank you @cc20101001 . I'll give it a think.
