### ISSUE TITLE
Allow @snoop without parentheses

### ISSUE THREAD

**Issue by alexmojaki** [cool-RR/PySnooper#69]
I think it would be good to allow:

```python
@snoop
def foo():
```

Instead of requiring

```python
@snoop()
def foo():
```

Any objections? I'm happy to do this.

**Comment by cool-RR** [comment]
It's cute. I guess you'll have to bring back the parentheses if you'll want arguments. As long as the code isn't too ugly, go ahead. I also hope it would interact gracefully with #65, once that's done.

**Comment by alexmojaki** [comment]
This is now impossible to do reliably since the output can be a function. The only option is to change the signature so that `output` is passed as a keyword argument, e.g.

    @snoop(output='file')

Maybe just call it `out`.

**Comment by cool-RR** [comment]
Nice observation. I think there is no choice but to close this feature request.
