### ISSUE TITLE
Adding to list may not trigger modified var line

### ISSUE THREAD

**Issue by alexmojaki** [cool-RR/PySnooper#73]
Example script:

```python
import pysnooper

@pysnooper.snoop()
def foo():
    x = []
    for i in range(10):
        x.append(i)

foo()
```

Output:

```
13:38:44.029228 call         5 def foo():
13:38:44.029456 line         6     x = []
New var:....... x = []
13:38:44.029540 line         7     for i in range(10):
New var:....... i = 0
13:38:44.029621 line         8         x.append(i)
Modified var:.. x = [0]
13:38:44.029688 line         7     for i in range(10):
Modified var:.. i = 1
13:38:44.029751 line         8         x.append(i)
Modified var:.. x = [0, 1]
13:38:44.029816 line         7     for i in range(10):
Modified var:.. i = 2
13:38:44.029880 line         8         x.append(i)
Modified var:.. x = [0, 1, 2]
13:38:44.029948 line         7     for i in range(10):
Modified var:.. i = 3
13:38:44.030015 line         8         x.append(i)
Modified var:.. x = [0, 1, 2, 3]
13:38:44.030083 line         7     for i in range(10):
Modified var:.. i = 4
13:38:44.030150 line         8         x.append(i)
Modified var:.. x = [0, 1, 2, 3, 4]
13:38:44.030220 line         7     for i in range(10):
Modified var:.. i = 5
13:38:44.030290 line         8         x.append(i)
Modified var:.. x = [0, 1, 2, 3, 4, 5]
13:38:44.030364 line         7     for i in range(10):
Modified var:.. i = 6
13:38:44.030436 line         8         x.append(i)
Modified var:.. x = [0, 1, 2, 3, 4, 5, ...]
13:38:44.030508 line         7     for i in range(10):
Modified var:.. i = 7
13:38:44.030580 line         8         x.append(i)
13:38:44.030638 line         7     for i in range(10):
Modified var:.. i = 8
13:38:44.030712 line         8         x.append(i)
13:38:44.030770 line         7     for i in range(10):
Modified var:.. i = 9
13:38:44.030843 line         8         x.append(i)
13:38:44.030901 line         7     for i in range(10):
13:38:44.030960 return       7     for i in range(10):
```

Partway through `x` seems to stop changing and the user might be misled into thinking it has, which could be a serious problem when trying to figure out a bug. Here it's obvious but in a more complex script it may not be.

Or suppose the user is building up a list of strings to make a document and does this:

    lines += doc.get_footer()

where `get_footer` is an abstract method and may return an empty list. The user has to debug further to know if anything changed.

**Comment by cool-RR** [comment]
Good catch. Unfortunately I can't think of a good solution. So unless you have one, I suggest you close this bug and users will just have to deal.

**Comment by alexmojaki** [comment]
You can override `_repr_iterable`. It's not that hard and someone can do it, but I've had enough here.

Of course it's solved in #68.

**Comment by alexmojaki** [comment]
Why close it? It's a bug, and someone else willing to contribute can solve it.

**Comment by cool-RR** [comment]
Because currently there isn't a solution that's better than the problem,
and we have no evidence that real-world users will experience this problem.

**Comment by alexmojaki** [comment]
>Because currently there isn't a solution that's better than the problem,

I don't know what this means.

**Comment by cool-RR** [comment]
It means that a solution could cause a problem that's worse than the
original problem.
