### ISSUE TITLE
Runtime error (IronPython)

### ISSUE THREAD

**Issue by runxel** [cool-RR/PySnooper#75]
I get the following runtime error with the demo code provided in the readme:
```
Runtime error (MissingMemberException): 'NoneType' object has no attribute 'get'
Traceback:
  line 72, in decorate, "pysnooper.py"
  line 59, in get_source_from_frame, "pysnooper\tracer.py"
  line 209, in trace, "pysnooper\tracer.py"
  line 2, in number_to_bits, "<decorator-gen-10>"
  line 20, in script
```
(line 20 calls the "number_to_bits" function)

**Comment by cool-RR** [comment]
Please specify iron python version

**Comment by runxel** [comment]
@cool-RR 

> 2.7.8 (IronPython 2.7.8 (2.7.8.0) on .NET 4.0.30319.42000 (64-bit))

**Comment by cool-RR** [comment]
Which version of PySnooper?

**Comment by runxel** [comment]
Downloaded from Github 4 days ago.

**Comment by cool-RR** [comment]
Give me the version number, use `pip freeze`

**Comment by runxel** [comment]
Ah, I didn't use pip. Basically because you can't use pip for that.
When using Grasshopper (part of the NURBS modeling software Rhino) you have to manually download and reference any third-party modules one would like to use.

**Comment by cool-RR** [comment]
I believe I fixed it. Try the new release and please report back.

@bittner It won't be easy to set up Travis to test on IronPython, right?

**Comment by runxel** [comment]
Interestingly it now says illegal char in path.... 🤔 
```
Runtime error (ArgumentException): Illegales Zeichen im Pfad.
Traceback:
  line 75, in inner, "pysnooper.py"
  line 110, in get_source_from_frame, "tracer.py"
  line 229, in trace, "tracer.py"
  line 2, in number_to_bits, "<decorator-gen-2>"
  line 19, in script
```

**Comment by alexmojaki** [comment]
@cool-RR if you're going to chase this, it might save you time not to release a version at each iteration, since @runxel is installing from GitHub anyway.

**Comment by runxel** [comment]
True, I will just clone it :)

Thank you very much already for looking into this crude edge cases!

**Comment by bittner** [comment]
> @bittner It won't be easy to set up Travis to test on IronPython, right?

IronPython is Windows, and Windows environments are not provided by Travis. We can do AppVeyor, though. Just like with PythonTurtle.

**Comment by cool-RR** [comment]
@bittner there's mono for Linux though, isn't there?

**Comment by cool-RR** [comment]
@runxel could you fetch the path that includes the illegal path? Like put a
print statement just before the line that fails?

**Comment by bittner** [comment]
> Like put a print statement just before the line that fails?

LOL  :rofl:

**Comment by cool-RR** [comment]
Haha yeah, the irony is not lost on me :)

And also:
https://mail.python.org/pipermail/python-ideas/2019-April/056443.html

If anyone's interested, it'll be cool to write a PEP for this.

**Comment by runxel** [comment]
So, what baffles me is that I am completely lost _what path_ it's talking about.
Also looking into your code gives me no hints to **what** to print.
(Or can I somehow insert something like `print` into your code, and get that output?)

> @runxel could you fetch the path that includes the illegal path? Like put a print statement just before the line that fails?

**Comment by cool-RR** [comment]
@runxel See the line `with open(file_name, 'rb') as fp:` ? The `file_name` argument probably has an illegal character or something. Add a line just before that line to print `file_name`, or write it to a file.

**Comment by runxel** [comment]
Ach, totally forgot I could write to a file – my bad!
So using `file.write(file_name)` I obtained this content:
`<string><string>`
This is literally the whole text file. 😨

**Comment by cool-RR** [comment]
I'm trying to reproduce this, but I'm not getting the `ArgumentException` that you're getting. I didn't even know it existed. Can you catch it as `e` and then print more information about it, especially `e.mro()`?

**Comment by runxel** [comment]
Now that was a fun story:  
To actually catch the ArgumentException I had to say
```python
# line 109 ff. in tracer.py
try:
    # foo
except Exception as e:
    # pass
```
And by that alone the error was gone!  
Which actually makes pretty much sense. You have **2** `if source is None` there. We are in the first `if` and in it there we get into the `else` condition – We can never reach the second `if source is None`.  
It then tries to write to a file with a path which is nonexisting and the `ArgumentException` gets not handled, only `OSError` and `IOError`.  
Maybe this section should be revised.  

Since we can never save the actual Python script in Grasshopper but stuff it into a component (Grasshopper is a node-based visual scripting environment) there will be never a filename.

Of course the `except Exception` is not a smart thing to do in the real world. The culprit is already in `file_name = frame.f_code.co_filename` where it is assumed, that this will always give a valid file name. As mentioned above this is not always the case, since the user might run scripts in arbitrary environments.  
I'm not sure if we can detect such cases correctly. The other fix would be checking `file_name` against `<string>` as content. (I had a mistake there above because I wrongly used `a` instead of `w` as the file open argument. So `frame.f_code.co_filename` interestingly gives this non-empty empty content.)

**Comment by cool-RR** [comment]
I think you're making a couple of mistakes there. Yes, I know we have to catch more than `OSError` and `IOError`, the question is what is that error, because `ArgumentException` is not a Python error.

Please try adding `ValueError` to the `except` clause at line 112 and tell me whether that solves your problem.

**Comment by runxel** [comment]
Right, there is no `ArgumentException`; I guess it comes from C# since Rhino/Grasshopper boils down to this in the end.  
Yes, `ValueError` will do the job!

**Comment by cool-RR** [comment]
Great, I released a new version, please try it and update here.

**Comment by runxel** [comment]
Works gracefully!  
Thank you so much :)

**Comment by cool-RR** [comment]
Awesome, this was a fun bug :)

There should also be an open bug on IronPython for raising `ValueError`,
but I'm gonna let the universe handle that one :D
