### ISSUE TITLE
add support for thread identifiers

### ISSUE THREAD

**Issue by zzzeek** [cool-RR/PySnooper#79]
pysnooper is amazing for the case where we are trying to see where threads are waiting on things.    If I can get the thread identifier in the output as an option, that makes this great.  Here's a hack that makes it work at the moment:

```diff
diff --git a/pysnooper/tracer.py b/pysnooper/tracer.py
index c4f4407..a5768f2 100644
--- a/pysnooper/tracer.py
+++ b/pysnooper/tracer.py
@@ -4,6 +4,7 @@
 import sys
 import re
 import collections
+import threading
 import datetime as datetime_module
 import itertools
 try:
@@ -226,6 +227,7 @@ class Tracer:
         ### Finished newish and modified variables. ###########################
 
         now_string = datetime_module.datetime.now().time().isoformat()
+        tid_string = threading.get_ident()
         line_no = frame.f_lineno
         source_line = get_source_from_frame(frame)[line_no - 1]
 
@@ -251,7 +253,7 @@ class Tracer:
         #                                                                     #
         ### Finished dealing with misplaced function definition. ##############
 
-        self.write('{indent}{now_string} {event:9} '
+        self.write('{indent}{now_string} {tid_string} {event:9} '
                    '{line_no:4} {source_line}'.format(**locals()))
 
         if event == 'return':

```

**Comment by cool-RR** [comment]
Sounds good. If you're interested, write a PR with a Boolean argument to
snoop, and tests. Ensure you've got padding on the thread ID to keep the
columns good.

**Comment by alexmojaki** [comment]
Perhaps it would be better to allow passing a callable (e.g. `threading.ident`) to `prefix`. More flexible, doesn't increase the number of parameters.

**Comment by cool-RR** [comment]
It's a bit hacky in my opinion. Also they'd have to write the padding logic
themselves.

**Comment by alexmojaki** [comment]
> Also they'd have to write the padding logic themselves

Why? Just use `prefix = self.prefix().strip() + ' '`.

**Comment by cool-RR** [comment]
The point with padding is to have a consistent width even if the length of
the data changes, to keep the columns lined up.

**Comment by alexmojaki** [comment]
Sorry, wasn't thinking straight.

`get_ident()` just returns a number, which is not very useful to humans. We'd probably want to include the name of the current thread too.

**Comment by alexmojaki** [comment]
This can be closed.
