### ISSUE TITLE
allow arbitrary callables, perhaps io / file objects, Python loggers for writers

### ISSUE THREAD

**Issue by zzzeek** [cool-RR/PySnooper#80]
Looking at https://github.com/cool-RR/PySnooper/blob/master/pysnooper/pysnooper.py#L13 I see our choices for "writier" are, stdout, path to a filename and something called "WritableStream"  .   In our case we have an application that's running under mod_wsgi, so we want to go to a logger.      Since PySnooper's great talent is being able to get deep into a huge stack without any hassle, being able to send the string output anywhere is important.   There are threadsafe loggers as well and things like that which follow built-in conventions like [IO](https://docs.python.org/3/library/io.html), or just a plain Python callable where we can plug anything we want.

**Comment by zzzeek** [comment]
I can PR these things if you are OK with it.

**Comment by cool-RR** [comment]
Allowing a callable is a great idea. Don't forget tests on your PR.

**Comment by alexmojaki** [comment]
To clarify, a `WritableStream` is literally any class with a 'write' method, so it's easy right now to send the output anywhere. But I agree allowing any callable will be convenient, which should be the aim of the library.

**Comment by zzzeek** [comment]
right I just realized that's what the ABC-ness of it does, so that is better.

**Comment by cool-RR** [comment]
Mike, your idea is still good.
