### ISSUE TITLE
Suggestion: "pydoc pysnooper" should show how to use this

### ISSUE THREAD

**Issue by andreasvc** [cool-RR/PySnooper#83]

**Comment by cool-RR** [comment]
Can anyone explain what would be needed and what the benefits would be?

**Comment by andreasvc** [comment]
The benefit is that "pydoc" gives ... documentation. It's as simple as adding a docstring in __init__.py.

**Comment by cool-RR** [comment]
Like, documentation that you'd have hosted on ReadTheDocs? I don't see the big advantage. PySnooper is very simple and all the documentation fits in the readme, maybe we'll make another text file for advanced usage but that's it.

**Comment by andreasvc** [comment]
No, the usage instructions from the readme would be enough.
The advantage is that docstrings can be read by pydoc, ipython, jupyter,
etc. Makes documentation more easily discoverable because you don't have
to open a web browser and search.

**Comment by cool-RR** [comment]
Okay, cool. Feel free to submit a PR. Just a few lines and a link to the
readme for the rest. (I don't want to have to update the docstring too
often.)
