### ISSUE TITLE
Improve "Advanced Usage" in readme

### ISSUE THREAD

**Issue by cool-RR** [cool-RR/PySnooper#84]
The "Advanced Usage" section in the readme is really unclear.

We need an example of `watch_explode`, and separately an example of one of the special Variable classes.

**Comment by cool-RR** [comment]
@alexmojaki You can take this if you're interested.

**Comment by alexmojaki** [comment]
I think you'll need to explain what's unclear. `watch_explode` isn't meant to be covered in Advanced Usage, the explanation is under Features:

> Expand values to see all their attributes or items of lists/dictionaries

which is intentionally very concise, and should be sufficient. If it's not, that needs to be addressed. Beyond that, my thinking then is that people will:

1. Try to use `watch_explode` with a string
2. Hit a problem, e.g. the wrong kind of expansion or too much data
3. Look at the README or docstring where they first saw `watch_explode` mentioned
4. Go to Advanced Usage as directed
5. See how to solve the problem they have, by either:
  a. Specifying a class (I think it's pretty clear which to choose if you have a goal in mind)
  b. Specifying `exclude` if a certain attribute is annoying them
  c. Adding a slice if their logs are flooded with list items

**Comment by cool-RR** [comment]
It's okay that the instructions section has just one sentence about `watch_explode` (also I'd stress that the attributes/items are shown *separately*, which is really the thing that makes it different,) but I think that the Advanced Usage part should have an example, because it's not easy to understand.

**Comment by alexmojaki** [comment]
There is an example. Do you mean a full script and its output?

**Comment by cool-RR** [comment]
Not a full script and output, but just 2-3 lines of output of the attributes/indices. Otherwise lots of people will have no idea what this does.

**Comment by alexmojaki** [comment]
I suggest you go ahead and do this because I'm really not getting your vision and talking about it isn't working.
