### ISSUE TITLE
Repeatedly opening a file is very slow

### ISSUE THREAD

**Issue by alexmojaki** [cool-RR/PySnooper#89]
This:

```python
from littleutils import timer

import pysnooper

f = open('/tmp/snoop2', 'w')

@pysnooper.snoop(f.write)
def foo():
    for i in range(10000):
        pass

with timer():
    foo()

f.close()
```

is about 10 times faster than this:

```python
from littleutils import timer

import pysnooper

@pysnooper.snoop('/tmp/snoop')
def foo():
    for i in range(10000):
        pass

with timer():
    foo()
```

**Comment by alexmojaki** [comment]
I'm willing to tackle this, will do some refactoring along the way.

**Comment by cool-RR** [comment]
I don't think it's a meaningful concern. These "10 times faster"
comparisons seem impressing, but 10K lines is a lot of lines, and I bet it
still ran pretty fast.

**Comment by cool-RR** [comment]
Also consider that keeping the file open can be a problem if it's a log
files that others also write to.

**Comment by alexmojaki** [comment]
> but 10K lines is a lot of lines

No one is going to read all those lines, but they might still output that many even if they're just interested in what's at the end or the beginning. After all, the idea is to just slap on a decorator without any effort such as splitting up a function. Or they might be grepping for something.

> I bet it still ran pretty fast.

It was about 6 seconds vs 0.6 seconds. Of course it could be much longer, especially if the loop contains many lines and changing (particularly exploded) variables.

> if it's a log files that others also write to.

Do you think we should be supporting such use cases? It seems like a very weird thing to do. And the current implementation could still have that problem. Let me know if you think this is a dealbreaker so I don't make the changes.

**Comment by cool-RR** [comment]
I prefer to keep opening the file every time.
