### ISSUE TITLE
Show the shape of numpy array & tensorflow Tensor

### ISSUE THREAD

**Issue by ysw361564483** [cool-RR/PySnooper#94]
Is there any solution to show the variable shape directly?

**Comment by cool-RR** [comment]
Maybe you can make your own function `show` and then pass `watch='show(my_array)'` to PySnooper. Other than that I don't want to add special cases.

**Comment by alexmojaki** [comment]
`watch='arr.shape'` should work.

**Comment by jh-yi** [comment]
I'm also looking for the answer. And here might be one possible solution: (at least works in my case)

1. Go to the declaration of function **_pysnooper.snoop()_**  (in Pycharm, just ctrl+B+single click this function)
2. Go to the declaration of class **_Tracer_** (line 69 in pysnooper.py)
Or you can directly find the file in path_to_env_where_you_install_pysnooper_/env_name/lib/python2.7/site-packages/pysnooper/tracer,py (python2.7 for example)

3. Modifiy following sentences:
<pre name="code" class="python"> 
# Line: 273
self.write('{indent}{newish_string}{name} = {value_repr}'.format(**locals()))

# replace with
try:
    `self.write('{indent}{newish_string}{name} = {}, {value_repr}'.format(locals()['frame'].f_locals[name].shape, **locals()))   `
except AttributeError:   
    self.write('{indent}{newish_string}{name} = {value_repr}'.format(**locals()))`
</pre>
and 
<pre name="code" class="python"> 
# Line: 276
self.write('{indent}Modified var:.. {name} = {value_repr}'.format(**locals()))

# replace with
try:
    self.write('{indent}Modified var:.. {name} = {}, {value_repr}'.format(locals()['frame'].f_locals[name].shape, **locals()))
except AttributeError:
    self.write('{indent}Modified var:.. {name} = {value_repr}'.format(**locals()))
</pre>

hope this helps.

**Comment by cool-RR** [comment]
I think you'll be better off monkeypatching `get_shortish_repr`. (Ensure you're on the latest PySnooper version.)
