### ISSUE TITLE
Exception on overwrite=True seems harsh

### ISSUE THREAD

**Issue by alexmojaki** [cool-RR/PySnooper#95]
Talking about this:

```python
    if truncate is None and overwrite:
        raise Exception("`overwrite=True` can only be used when writing "
                        "content to file.")
```

I agree with this kind of check in more 'serious' code intended for production. It ensures that the user understands what they're doing.

But in this case it's harmless and the user will only be annoyed by the exception if, say, they decide to go from writing to a file back to stderr and forget to delete the argument. I don't think anyone is going to think they can overwrite stderr (what would that mean?) and get confused when that doesn't happen. Just document "this argument only has an effect when output is a file path".

Speaking of which, `overwrite` should probably be documented. Maybe under Advanced Usage.

**Comment by cool-RR** [comment]
I disagree on both counts. This is really an edge case and not worth making
a change.
