### ISSUE TITLE
Support for Other Languages

### ISSUE THREAD

**Issue by guanw** [cool-RR/PySnooper#98]
Hi, folks. This project looks very helpful to people who are new to programming. Just want to say Great job and I'm curious have you thought about doing similar stuff for other languages? In particular I'm thinking of golang. 

I notice golang has some really good metrics and profiling method but in terms of exposing variable valuesi don't think there's any existing tool.(I notice there's `runtime` and `expvar` in golang but not targeting at logging every change as program runs) Let me know your thoughts about it. Thanks.

**Comment by cool-RR** [comment]
Thanks!

Because this tool is so reliant on the tooling given by Python
(sys.settrace), any tool for a different language will be so radically
different that it should definitely be a completely separate project. Feel
free to start one :)

**Comment by guanw** [comment]
Yeah. That sounds totally right. I'm going to do some experiment to see if there's a good way to do it in golang. Cheers!
